apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 1   # Quantos pods queremos rodando
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: hashicorp/http-echo  # A imagem container
        args: 
        - "-text=Hello, Kubernetes com ArgoCD!"
        ports:
        - containerPort: 5678      # Porta que o container escuta