apiVersion: v1
kind: Service
metadata:
  name: hello-app
spec:
  type: ClusterIP     # Disponível apenas dentro do cluster
  selector:
    app: hello-app
  ports:
  - protocol: TCP
    port: 80           # Porta interna no cluster
    targetPort: 5678   # Porta do container